name: Run Stack Analyser
author: Specfy
description: |-
  Analyse your stack and save output to a file. Detect Languages, SaaS, Cloud, Infrastructure, Dependencies, etc.


runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'box'
  color: 'white'
